### ISSUE TITLE
goal: 486, 686, 686-pae, amd64 compatibility?

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Gentoo-Port#4]
Related to #3.

What platform should we initially support?

Downloadable Whonix 9.x based on Debian are using arch `i386` and come with a `486` kernel for compatibility as well as with a `686-pae` kernel for most users. Builders from source have the option to go for `amd64` and other stuff.

**Comment by martinholovsky** [comment]
Hi,

same as my reply in #3.

Thank you

**Comment by an0ncs0** [comment]
amd64 is necessary.

**Comment by adrelanos** [comment]
Good, so we can drop "486, 686, 686-pae". That makes bootling a lot easier.

**Comment by adrelanos** [comment]
Noted here:
https://www.whonix.org/wiki/Dev/Gentoo
