### ISSUE TITLE
goal: use of binary packages during build process allowed?

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Gentoo-Port#5]
Can we use https://en.wikipedia.org/wiki/Portage_%28software%29#Binary_packages in the build script to ease and speed up development and image building?

**Comment by martinholovsky** [comment]
Hi,

same as my reply in #3.
Please read wiki one more time. This is possible just for "identical systems".
We can setup server which will be compiling some very common (=without performance) type of amd64 system if you mean it in this way.

Anyway, is the build process really that much slow?

Thank you

**Comment by adrelanos** [comment]
Does Gentoo offer any official binary packages for download?

**Comment by martinholovsky** [comment]
Just for very common packages like firefox, libreoffice, etc., but for identical systems you can make your own binary packages for whatever you want

S pozdravem / Best regards,
Martin Čmelík

**Comment by adrelanos** [comment]
Martin Čmelík:

> Just for very common packages like firefox, libreoffice, etc.,

That's my critical point here.

Are we allowed to use those packages to ease and speed up development
and image building?

**Comment by martinholovsky** [comment]
It depend what packages you need, as Securix itself is not using common packages with binary aletrnative known to me.

S pozdravem / Best regards,
Martin Čmelík

**Comment by adrelanos** [comment]
Is there a list of available binary packages from official gentoo
repositories?

**Comment by martinholovsky** [comment]
More information here:
http://www.gentoo-wiki.info/TIP_Providing_binary_packages

**Comment by martinholovsky** [comment]
Here is the trick:
Visit http://packages.gentoo.org
Search: "-bin"

**Comment by adrelanos** [comment]
> More information here:
> http://www.gentoo-wiki.info/TIP_Providing_binary_packages

That could be useful for continued runs of the build script (debugging), to speed up building.

**Comment by martinholovsky** [comment]
Thats right
Not only for build, but for additional applications required by Whonix as well

**Comment by an0ncs0** [comment]
1st security
2nd performance
3rd ease of use / functionality

**Comment by adrelanos** [comment]
Sponsor B said, usage of these packages is okay. (But overall the goal is to install form source.)

**Comment by martinholovsky** [comment]
please close it then

**Comment by adrelanos** [comment]
Outcome of this ticket is summarized here:
https://www.whonix.org/wiki/Dev/Gentoo
