### ISSUE TITLE
securix-control install.sh security

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Gentoo-Port#6]
I am not sure yet, but (parts of) securix-control install.sh might be helpful for #1? Had a quick look.

There might be some security issues with:
https://github.com/martincmelik/securix-control/blob/master/install.sh

Please check out the TUF threat model (See Attacks and Weaknesses):
https://github.com/theupdateframework/tuf/blob/develop/SECURITY.md

Function `f_download` might be vulnerable to man-in-the-middle attacks. Ideally it would enforce ssl (if available) as well as verify (gpg) signatures.

(shellcheck (http://www.shellcheck.net/) (Libre Software, online service + downloadable) might also point out some results.)

**Comment by martinholovsky** [comment]
GPG is verified

**Comment by adrelanos** [comment]
Where? The whole file https://github.com/martincmelik/securix-control/blob/master/install.sh does not contain the word "gpg".

**Comment by martinholovsky** [comment]
This file is two years old...
repo deleted, I will upload latest version soon
