### ISSUE TITLE
Generic Packaging Discussion

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Gentoo-Port#9]
Whonix's packages (that mostly contain just scripts, config files and package dependencies) are mostly packaged using "[generic packaging](https://github.com/Whonix/anon-gw-anonymizer-config#generic-packaging)". It's about where files are stored, how the makefile works and distribution specific packaging tools.

In short, files in `etc/...` in root source folder will be installed to `/etc/...`, files in `usr/...` will be installed to `/usr/...` and so forth. This should make renaming, moving files around, packaging, etc. very simple. Packaging of most of Whonix's packages ([list](https://github.com/Whonix)) looks very similar.

The [makefile](https://github.com/Whonix/anon-gw-anonymizer-config/blob/master/Makefile), the [make-helper.bsh](https://github.com/Whonix/anon-gw-anonymizer-config/blob/master/make-helper.bsh) script are the same for any package and other files (such as licensing stuff) look very similar.

This makes packaging and maintenance real simple.

Does that explanation and method make sense to you, @martincmelik?

You can image why I am asking, because I want to think through how to package Whonix's packages also as Gentoo ebuilds, as generically as possible, so maintenance effort will be low. I plan to elaborate on that as soon as we're on the same page.

Do you have experience creating Gentoo ebuilds?

**Comment by martinholovsky** [comment]
Hi,

I do not have experience with gentoo ebuild, but until they will support ebuild signing, then I think you will not be willing to use that as well.

Thank you

**Comment by adrelanos** [comment]
> but until they will support ebuild signing, then I think you will not be willing to use that as well

Created a ticket for that to figure that out:
https://github.com/Whonix/Gentoo-Port/issues/10

---

As for purpose of packaging Whonix's packages as ebuilds, it would not be that important if they are signed or not. I am referring to ebuilds here only as the counterpart of .deb packages. Using them as a vehicle to get files installed to proper places and updated from source code. The ebuilds being unsigned for that very purpose would be no issue, if creation of the packages (ebuilds) happens locally by the build script. So when users build or update Whonix package ebuilds from source code, it would not matter if they are signed or not.

(Securely obtaining packages from Gentoo is another story that I would like to discuss here: https://github.com/Whonix/Gentoo-Port/issues/10)

Does that make sense?

---

Any other questions on the generic packaging thing?

**Comment by martinholovsky** [comment]
I'm not sure if you didn't mention it yet, but I think that for Whonix might fit to use own overlay
more info here: http://wiki.gentoo.org/wiki/Overlay
and here: http://www.gentoo.org/proj/en/overlays/devguide.xml

**Comment by adrelanos** [comment]
An `overlay` repository seems to be the equivalent to a Debian `apt` repository. I'd consider using a local `overlay` for installing Whonix ebuilds during the build. Before an overlay could be created, Whonix's would have to be packaged as `ebuilds`.

Looks like there are some people who use `apt-get`, `dpkg` and `deb` packages on Gentoo systems. Maybe that could be simpler than porting to `ebuilds` + `overlay`.

**Comment by adrelanos** [comment]
Having discussed that, let's create new tickets for TODO's.
